name: CCCore
version: 1.1.0
main: com.henhen1227.cccore.CCCore
api-version: '1.20'
load: STARTUP
authors: [Henry Abrahamsen]
description: All the necessary components for Chicken Craft to work
website: https://mc.henhen1227.com
commands:
  points:
    description: Modify the number of points a player has.
    usage: /points { award|revoke } <player> <amount>
  cccore:
    description: Root of all Chicken Craft Core non-admin commands.
    usage: /cccore
  reloadws:
    description: Reload Websocket Server.
    usage: /reloadws
  startchatgame:
    description: Start a chat game.
    usage: /startchatgame [game]
  startevent:
    description: Start an event.
    usage: /startevent [event]
  leave:
    description: Leave game or lobby.
    usage: /leave
  shop:
    description: Open CCCore's Shop UI.
    usage: /shop
  spawntrader:
    description: Spawn villager with custom UI.
    usage: /spawntrader <trader>
  competition:
    description: See the current competition and its standings.
    usage: /competition
  startcompetition:
    description: Start a competition with specific id.
    usage: /startcompetition <competition_id>
  endcompetition:
    description: End the current competition and assign winner.
    usage: /endcompetition
permissions:
  cccore.default.use:
    description: Grants user access to basic Chicken Craft Core commands
    default: true
  cccore.shop.use:
    description: Grants user access to Chicken Craft Core's Shop UI
    default: op
  cccore.admin.use:
    description: Grants user access of all Chicken Craft Core admin commands
    default: op
  cccore.dropitems.bypass:
    description: Allows user to drop items even when not prevented during events.
    default: op
  cccore.admin.errors:
    description: Allows the user to see errors in the console
    default: op